// src/app/layout.js
import Footer from './_footer/Footer';
import Header from './_header/Header';
import ClientLayout from './ClientLayout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <Header/>
          {children}
          <Footer/>
        </ClientLayout>
      </body>
    </html>
  );
}
